### ISSUE TITLE
TypeError: Two is not a constructor

### ISSUE THREAD

**Issue by rishanbenahalkar** [SrWhale/disgames#1]
I've done what the NPM readme.md file says but yet I am faced with this error, I looked through the code yet I could not resolve the issue being faced, here is my code:

```js
const { MessageEmbed } = require("discord.js");
const SlashCommand = require("../../lib/SlashCommand");
const { Two } = require('disgames');

const command = new SlashCommand()
  .setName("2048")
  .setDescription("Play a game of 2048!")
  .setRun(async (client, interaction) => {
	 try {
		new Two({
            interaction,
            size: 4
        }).play()
     } catch (error) {
	interaction.reply({ embeds: [client.ErrorEmbed(error)] })
	    }
  });

module.exports = command;
```

**Comment by SrWhale** [comment]
Sorry for the delay in responding, but this repository is deprecated and inactive.

**Comment by SrWhale** [comment]
Closing!

**Comment by SrWhale** [comment]
Closing!

**Comment by SrWhale** [comment]
> I've done what the NPM readme.md file says but yet I am faced with this error, I looked through the code yet I could not resolve the issue being faced, here is my code:
> 
> ```js
> const { MessageEmbed } = require("discord.js");
> const SlashCommand = require("../../lib/SlashCommand");
> const { Two } = require('disgames');
> 
> const command = new SlashCommand()
>   .setName("2048")
>   .setDescription("Play a game of 2048!")
>   .setRun(async (client, interaction) => {
> 	 try {
> 		new Two({
>             interaction,
>             size: 4
>         }).play()
>      } catch (error) {
> 	interaction.reply({ embeds: [client.ErrorEmbed(error)] })
> 	    }
>   });
> 
> module.exports = command;
> ```

Closing!
